# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZrOiXBUTdDSTRAgMXXEbkrvr01MSogz
"""

import pandas as pd

def load_and_clean_data():
    # Load both Excel files
    grassland_df = pd.read_excel("Bird_Monitoring_Data_GRASSLAND.XLSX")
    forest_df = pd.read_excel("Bird_Monitoring_Data_FOREST.XLSX")

    # Add habitat column to differentiate data
    grassland_df['Habitat'] = 'Grassland'
    forest_df['Habitat'] = 'Forest'

    # Combine datasets
    df = pd.concat([grassland_df, forest_df], ignore_index=True)

    # Convert Date column
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month

    # Handle missing values
    if 'Temperature' in df.columns:
        df['Temperature'] = df['Temperature'].fillna(df['Temperature'].mean())
    if 'Humidity' in df.columns:
        df['Humidity'] = df['Humidity'].fillna(df['Humidity'].mean())

    return df